[package]
name = "uds-server"
version = "0.1.0"
edition = "2021"
publish = false

[dev-dependencies]
criterion = { version = "0.3.5", default-features = false }

[[bench]]
name = "uds"
harness = false

[[bin]]
name = "client"
path = "src/client.rs"

[[bin]]
name = "server"
path = "src/server.rs"
